# syntax=docker/dockerfile:1

# === Base Image ===
FROM golang:1.25.3-alpine3.22 AS builder 

WORKDIR /build

RUN apk add --no-cache git

# === Build Application ===
# cache layer
COPY go.mod go.sum ./
RUN go mod download

# kopiowanie reszty plików źródłowych
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o /app/service ./cmd/server/main.go


# === Final Image ===
FROM alpine:latest

# Instalacja ca-certificates (https) i timezone data
RUN apk --no-cache add ca-certificates tzdata

# non-root user
RUN addgroup -g 1000 appuser && \
    adduser -D -u 1000 -G appuser appuser

WORKDIR /app

# Kopiowanie skompilowanego pliku binarnego z etapu budowania
COPY --from=builder /app/service .

# Kopiowanie migracji bazy danych
COPY --from=builder /build/migrations ./migrations

# Zamiana uprawnnień na non-root user
RUN chown -R appuser:appuser /app

# Przełączanie na non-root user
USER appuser

# Expose port
EXPOSE 8080

# Healthcheck
HEALTHCHECK --interval=30s --timeout=3s \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1


# Uruchomienie aplikacji
CMD ["./service"]